import algorithm.RSA;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) {
        RSA rsa = new RSA();

        System.out.println("Running RSA test");
        long startTime = System.currentTimeMillis();
        rsa.runTest();
        long endTime = System.currentTimeMillis();
        long timeSpent = endTime - startTime;
        System.out.println("Time spent: " + timeSpent);
    }
}
